### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by jessicagrayson** [jessicagrayson/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can interact with the registration form to create a new account

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to post new user to database
- [x] Create api endpoint
- [x] Hash password
- [x] Build sql object
- [x] Catch errors
- [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Create sign up components
- [x] Create logo
- [x]  Write fetch function to create new user from user input
- [x] Confirm new user is entered into database
- [x] Test
